language: erlang
addons:
  postgresql: "9.1"
#
before_script:
  - cp etc/tileman.conf.travis config/tileman.conf
  - psql -U postgres -c "create extension postgis"
  - psql -c 'create database gis;' -U postgres
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq python-software-properties lsb-release"
  - "sudo apt-add-repository -y ppa:osmjapan/ppa"
  - "sudo apt-get update -qq"
  - "sudo apt-get install -qq nginx-openresty ttf-unifont ttf-dejavu ttf-dejavu-core ttf-dejavu-extra"
  - "sudo apt-get install -qq --no-install-recommends osm2pgsql tirex-core tirex-backend-mapnik tirex-example-map"
  - "sudo apt-get install -qq geoip-database lua5.1 lua-bitop openjdk-7-jre lua-nginx-osm"
  - "sudo apt-get install -qq libjs-leaflet"
  - "sudo apt-get install -qq --no-install-recommends openstreetmap-mapnik-stylesheet-data"
  - "sudo osmosis/osmosis-installer.sh"
install:
  - "sudo make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis install"
  - "sudo make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis travis_test_install"
# command to run tests
script:
  - "sudo make test_service_start"
  - "make PREFIX=/usr HTMLDIR=/var/www CONFDIR=/etc CACHEDIR=/var/cache/tileman STATICDIR=/var/lib/tileman/tiles WORKDIR=/var/lib/osmosis test"

